name: ZAntiCheat
version: '$version'
main: cn.jeyor1337.zanticheat.Main
api-version: '1.13'
folia-supported: true
softdepend: [ Geyser-Spigot, floodgate, ViaVersion, GSit, mcMMO, ValhallaMMO, VeinMiner, AureliumSkills, ExecutableItems, EnchantsSquared ]
description: A lightweight and customizable anticheat, designed to detect common hacks.
authors: [ Jeyor1337 ]
website: www.reworlds.net
commands:
  zanticheat:
    aliases: [ zac, anticheat, ac ]
  report:
    aliases: [ jb ]
permissions:
  zanticheat.checks:
    description: Allows /anticheat checks command
    default: op
  zanticheat.reload:
    description: Allows /anticheat reload command
    default: op
  zanticheat.alerts.notify:
    description: See debug messages
    default: op
  zanticheat.alerts.toggle:
    description: Allows /anticheat alerts command
    default: op
  zanticheat.alerts.teleport:
    description: Allows /anticheat teleport command
    default: op
  zanticheat.alerts:
    description: All of the alert permissions
    default: op
    children:
      zanticheat.alerts.notify: true
      zanticheat.alerts.toggle: true
      zanticheat.alerts.teleport: true
  zanticheat.client:
    description: Allows /anticheat client command
    default: op
  zanticheat.tps:
    description: Allows /anticheat tps command
    default: op
  zanticheat.ping:
    description: Allows /anticheat ping command
    default: op
  zanticheat.cps:
    description: Allows /anticheat cps command
    default: op
  zanticheat.report:
    description: Allows /report command
    default: op
  zanticheat.bypass:
    description: Bypass all the checks
    default: op
  zanticheat.*:
    description: All of all the above
    default: op
    children:
      zanticheat.checks: true
      zanticheat.reload: true
      zanticheat.alerts: true
      zanticheat.broadcast: true
      zanticheat.client: true
      zanticheat.tps: true
      zanticheat.ping: true
      zanticheat.cps: true
      zanticheat.report: true
      zanticheat.bypass: true
